### ISSUE TITLE
No falco_ctrl_EFC_schedule_generator() function

### ISSUE THREAD

**Issue by kian1393** [ajeldorado/falco-matlab#121]
I have recently installed FALCO and while trying to run the example WFIRST/Roman scripts, I have run into the issue of not knowing where this function is. The exact error message is shown below. 

![image](https://user-images.githubusercontent.com/50641386/94739317-a90ff280-0325-11eb-8b9a-55ef32f9c06c.png)

I have altered all the addpath() statements in the beginning of the file to the correct directory locations and I have looked through all the directories, but cannot seem to find this function in any of them.

**Comment by ajeldorado** [comment]
Try entering (replace path_to_falco with the actual path):
>> addpath(genpath(path_to_falco))

The function is located in falco-matlab/lib/wfsc/

**Comment by kian1393** [comment]
Thank you for the help, it did work.
